FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["ProcessingService/ProcessingService.csproj", "ProcessingService/"]
COPY ["Common/Common.csproj", "Common/"]
RUN dotnet restore "ProcessingService/ProcessingService.csproj"
COPY . .
WORKDIR "/src/ProcessingService"
RUN dotnet build "ProcessingService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ProcessingService.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ProcessingService.dll"]
